name: pgsql-test
networks:
  pgsql-test:
    name: pgsql-test
services:
  pgsql-test:
    image: postgres:18-trixie
    container_name: pgsql-test
    restart: unless-stopped
    networks:
      - pgsql-test
    environment:
      POSTGRES_USER: "${TEST_PG_USER}"
      POSTGRES_PASSWORD: "${TEST_PG_PASSWORD}"
      POSTGRES_DB: "${TEST_PG_DBNAME}"
    ports:
      - "${TEST_PG_HOSTPORT}:5432"
    volumes:
      - pgsql-test-data:/var/lib/postgresql

volumes:
  pgsql-test-data:
